import { calculateDamage, probabilitySummary } from './engine.mjs';
'use strict';
const STORE='maple-growth-lab-mvp-v1';
const DATA={combat:null,stats:null,jobs:null,probabilities:null};
const JOB_NAMES={hero:'히어로',paladin:'팔라딘',darkKnight:'다크나이트',archMageIceLightning:'아크메이지(썬·콜)',archMageFirePoison:'아크메이지(불·독)',bishop:'비숍',bowmaster:'보우마스터',sniper:'신궁',nightLord:'나이트로드',shadower:'섀도어',viper:'바이퍼',captain:'캡틴',nightWalker:'나이트워커',windBreaker:'윈드브레이커'};
const STAT_OPTIONS=[['NONE','없음'],['ATK_FLAT','공격력(+)'],['ATK_PCT','공격력%'],['MAIN_STAT_FLAT','주스탯(+)'],['MAIN_STAT_PCT','주스탯%'],['SUB_STAT_FLAT','부스탯(+)'],['DMG','데미지%'],['DMG_AMP','데미지 증폭%'],['FINAL_DMG','최종 데미지%'],['BOSS_DMG','보스 데미지%'],['NORMAL_DMG','일반 몬스터 데미지%'],['DEF_PEN','방어 관통력%'],['CRIT_RATE','크리티컬 확률%'],['CRIT_DMG','크리티컬 데미지%']];
const $=id=>document.getElementById(id); const n=id=>Number($(id)?.value||0); const clamp=(v,a,b)=>Math.min(b,Math.max(a,v)); const pct=v=>1+Number(v||0)/100; const fmt=v=>Number.isFinite(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:2}):'—';
function setStatus(text,kind=''){const el=$('dataStatus');el.textContent=text;el.className='status-strip '+kind;}
function snapshot(){const out={};document.querySelectorAll('input[id],select[id]').forEach(el=>{if(['presetName','presetSelect'].includes(el.id))return;out[el.id]=el.type==='checkbox'?el.checked:el.value});return out}
function applySnapshot(s){Object.entries(s||{}).forEach(([id,v])=>{const el=$(id);if(!el)return;if(el.type==='checkbox')el.checked=!!v;else el.value=v});renderAll();}
function saveLocal(){localStorage.setItem(STORE,JSON.stringify(snapshot()));}
function loadLocal(){try{const s=JSON.parse(localStorage.getItem(STORE)||'null');if(s)applySnapshot(s)}catch{}}
function profiles(){try{return JSON.parse(localStorage.getItem(STORE+'-profiles')||'{}')}catch{return {}}}
function saveProfiles(p){localStorage.setItem(STORE+'-profiles',JSON.stringify(p));renderProfileSelect()}
function renderProfileSelect(){const sel=$('presetSelect'),p=profiles();sel.innerHTML='<option value="">저장된 프리셋 없음</option>'+Object.keys(p).sort().map(k=>`<option value="${escapeHtml(k)}">${escapeHtml(k)}</option>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function optionSelect(value){return `<select class="option-stat">${STAT_OPTIONS.map(([id,label])=>`<option value="${id}" ${id===value?'selected':''}>${label}</option>`).join('')}</select>`}
function renderOptionRows(){for(const id of ['currentOptions','candidateOptions'])$(id).innerHTML=[0,1,2].map(i=>`<div class="option-row">${optionSelect('NONE')}<input class="option-value" type="number" step="0.01" value="0" aria-label="${id} 옵션 ${i+1} 값"></div>`).join('')}
function valuesFor(root){const out={};$(root).querySelectorAll('.option-row').forEach(row=>{const stat=row.querySelector('.option-stat').value;const val=Number(row.querySelector('.option-value').value||0);if(stat!=='NONE'&&val)out[stat]=(out[stat]||0)+val});return out}
function fillJobs(){const sel=$('job');const jobs=DATA.jobs?.jobs||{};Object.entries(jobs).forEach(([id])=>sel.insertAdjacentHTML('beforeend',`<option value="${id}">${JOB_NAMES[id]||id}</option>`))}
function readInputs(extra={}){const target=$('targetType').value;const job=DATA.jobs?.jobs?.[$('job').value]||{};const main=n('mainStat')*pct(n('mainStatPct'));const sub=n('subStat');const statBased=(main/100+sub/400);const stats={attackFlat:n('attackFlat'),attackPct:n('attackPct'),mainStat:main,subStat:sub,statBased,damage:n('damage'),damageAmp:n('damageAmp'),finalDamage:n('finalDamage'),critRate:n('critRate'),critDamage:n('critDamage'),minDamage:n('minDamage'),maxDamage:n('maxDamage'),mastery:n('mastery'),skillCoefficient:n('skillCoefficient'),attackInterval:n('attackInterval'),attackSpeed:n('attackSpeed'),targetDefense:n('targetDefense'),defPen:n('defPen'),bossDamage:n('bossDamage'),normalDamage:n('normalDamage'),targetTaken:n('targetTaken'),basicDamage:n('basicDamage'),skillDamage:n('skillDamage'),accuracy:n('accuracy'),target,job,level:n('level')};
  Object.entries(extra).forEach(([k,v])=>{if(k==='MAIN_STAT_FLAT')stats.mainStat+=v;else if(k==='MAIN_STAT_PCT')stats.mainStat*=pct(v);else if(k==='SUB_STAT_FLAT')stats.subStat+=v;else if(k==='ATK_FLAT')stats.attackFlat+=v;else if(k==='ATK_PCT')stats.attackPct+=v;else if(k==='DMG')stats.damage+=v;else if(k==='DMG_AMP')stats.damageAmp+=v;else if(k==='FINAL_DMG')stats.finalDamage+=v;else if(k==='BOSS_DMG')stats.bossDamage+=v;else if(k==='NORMAL_DMG')stats.normalDamage+=v;else if(k==='DEF_PEN')stats.defPen+=v;else if(k==='CRIT_RATE')stats.critRate+=v;else if(k==='CRIT_DMG')stats.critDamage+=v});
  stats.statBased=stats.mainStat/100+stats.subStat/400;return stats;
}
function calculate(extra={}){return calculateDamage(readInputs(extra), DATA.combat||{});}
function renderCombat(){const r=calculate();$('avgDamage').textContent=fmt(r.average);$('damageRange').textContent=`최소 ${fmt(r.min)} · 최대 ${fmt(r.max)}`;$('dps').textContent=fmt(r.dps);$('dpsNote').textContent=`공속 보정 ×${r.speedFactor.toFixed(3)} · 간격 ${n('attackInterval')}초`;$('defenseFactor').textContent=(r.defenseFactor*100).toFixed(2)+'%';$('defenseNote').textContent=`방어력 ${fmt(n('targetDefense'))} → 관통 후 ${fmt(r.afterDef)}`;$('statDamage').textContent=r.statBased.toFixed(2)+'%';$('combatBreakdown').innerHTML=`<div class="breakdown-grid"><span>공격력<b>${fmt(r.attack)}</b></span><span>치명타 기대 배율<b>×${(1+r.critChance*n('critDamage')/100).toFixed(3)}</b></span><span>대상 보정<b>${$('targetType').value==='boss'?n('bossDamage'):n('normalDamage')}%</b></span></div>`;saveLocal()}
function renderCube(){const current=calculate(valuesFor('currentOptions'));const candidate=calculate(valuesFor('candidateOptions'));$('cubeCurrentDps').textContent=fmt(current.dps);$('cubeCandidateDps').textContent=fmt(candidate.dps);const delta=candidate.dps-current.dps;const rate=current.dps?delta/current.dps*100:0;$('cubeDelta').textContent=`${delta>=0?'+':''}${fmt(delta)} (${rate>=0?'+':''}${rate.toFixed(2)}%)`;const p=n('cubeProbability')/100,cost=n('cubeCost');$('cubeEconomics').innerHTML=p>0?`후보 1회 달성 기대 횟수 <b>${fmt(1/p)}회</b> · 기대 메소 <b>${fmt(1/p*cost)}</b><br><small>확률이 없는 값은 기대 비용을 계산하지 않습니다.</small>`:'등장 확률을 입력하면 기대 횟수와 비용을 계산합니다.'}
function renderProbability(){const r=probabilitySummary(n('successRate'),n('attempts'),n('attemptCost'));if(!r.probability&&r.expectedAttempts===Infinity){$('probabilityResult').innerHTML='<div class="big-prob">0%</div>성공 확률이 0이면 달성 확률과 기대값은 계산할 수 없습니다.';return}$('probabilityResult').innerHTML=`<div class="big-prob">${(r.probability*100).toFixed(4)}%</div><ul><li>${r.attempts}회 안에 1회 이상 성공할 확률: <b>${(r.probability*100).toFixed(4)}%</b></li><li>평균 기대 시도 횟수: <b>${fmt(r.expectedAttempts)}회</b></li><li>평균 기대 비용: <b>${r.expectedCost==null?'미입력':fmt(r.expectedCost)}</b></li><li>90% 달성 필요 횟수: <b>${r.need90}회</b></li><li>95% 달성 필요 횟수: <b>${r.need95}회</b></li></ul>`}
function renderAll(){renderCombat();renderCube();renderProbability()}
async function loadData(){try{const [combat,stats,jobs,probabilities]=await Promise.all([fetch('data/combat-rules.json').then(r=>r.json()),fetch('data/stat-rules.json').then(r=>r.json()),fetch('data/job-stats.json').then(r=>r.json()),fetch('data/probabilities.json').then(r=>r.json())]);Object.assign(DATA,{combat,stats,jobs,probabilities});fillJobs();loadLocal();$('probabilitySource').textContent=`공식 설정 확률 데이터 로드 완료 · ${probabilities?.source?.verificationStatus||'검증 상태 확인 필요'}`;setStatus(`공식 전투·능력치·확률 데이터 로드 완료 · 직업 매핑은 ${jobs.status||'provisional'}`, 'good');renderAll()}catch(e){setStatus('데이터 파일을 불러오지 못했습니다. 기본 입력으로 계산하지만 공식 데이터 상태를 확인하세요.','bad');$('probabilitySource').textContent='확률 데이터 로드 실패: '+e.message;renderAll()}}
function bind(){document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===btn.dataset.tab))}));document.querySelectorAll('#characterForm input,#characterForm select,#targetForm input,#targetForm select').forEach(el=>el.addEventListener('input',renderCombat));$('calculateCombat').addEventListener('click',renderCombat);$('calculateCube').addEventListener('click',renderCube);$('calculateProbability').addEventListener('click',renderProbability);document.querySelectorAll('#currentOptions,#candidateOptions').forEach(el=>el.addEventListener('input',renderCube));$('saveQuick').addEventListener('click',()=>{saveLocal();$('activePresetLabel').textContent='현재 입력 저장됨';});$('resetAll').addEventListener('click',()=>{if(confirm('현재 입력을 초기화할까요?')){localStorage.removeItem(STORE);location.reload()}});$('savePreset').addEventListener('click',()=>{const name=$('presetName').value.trim();if(!name){alert('프리셋 이름을 입력하세요.');return}const p=profiles();p[name]=snapshot();saveProfiles(p);$('presetSelect').value=name;$('activePresetLabel').textContent=name;saveLocal()});$('loadPreset').addEventListener('click',()=>{const name=$('presetSelect').value,p=profiles();if(name&&p[name]){$('activePresetLabel').textContent=name;applySnapshot(p[name]);saveLocal()}});$('deletePreset').addEventListener('click',()=>{const name=$('presetSelect').value;if(!name)return;const p=profiles();delete p[name];saveProfiles(p);$('activePresetLabel').textContent='현재 입력'});}
renderOptionRows();renderProfileSelect();bind();loadData();renderAll();
