import { calculateCombatPower, calculateDamage, probabilitySummary } from './engine.mjs';
'use strict';
const STORE='maple-growth-lab-mvp-v1';
const DATA={combat:null,stats:null,jobs:null,probabilities:null,companionRuntime:null,companionRules:null,stageData:null};
const JOB_NAMES={hero:'히어로',paladin:'팔라딘',darkKnight:'다크나이트',archMageIceLightning:'아크메이지(썬·콜)',archMageFirePoison:'아크메이지(불·독)',bishop:'비숍',bowmaster:'보우마스터',sniper:'신궁',nightLord:'나이트로드',shadower:'섀도어',viper:'바이퍼',captain:'캡틴',nightWalker:'나이트워커',windBreaker:'윈드브레이커'};

const RUNTIME_JOB={hero:'hero',paladin:'paladin',darkKnight:'dark-knight',archMageIceLightning:'archmage-il',archMageFirePoison:'archmage-fp',bishop:'bishop',bowmaster:'bowmaster',sniper:'marksman',nightLord:'night-lord',shadower:'shadower',viper:'viper',captain:'captain',nightWalker:'night-walker',windBreaker:'wind-breaker'};
const EFFECT_LABEL={attackPlus:'공격력(+) ',maxDamage:'최대 데미지%',bossDamage:'보스 데미지%',normalDamage:'일반 몬스터 데미지%',basicDamage:'기본 공격 데미지%',skillDamage:'스킬 데미지%',attackSpeed:'공격 속도%',critRate:'크리티컬 확률%',critDamage:'크리티컬 데미지%',minDamage:'최소 데미지 배율%',mainPct:'주스탯%'};
function selectedCompanionEffect(){const presetEffect=window.MapleGrowthCompanion?.getEffect?.();if(presetEffect)return presetEffect;const rt=DATA.companionRuntime;if(!rt)return null;const job=RUNTIME_JOB[$('job')?.value];const grade=$('companionGrade')?.value;if(!job||!grade)return null;const rec=rt.equippedStats?.[job+':'+grade];if(!rec||!rec.levels?.length)return null;const level=clamp(n('companionLevel')||1,1,rec.levels.length);return {level,grade,record:rec,values:rec.levels[level-1]||{}}}
function renderCompanionEffect(){const c=selectedCompanionEffect(),box=$('companionEffect');if(!box)return;if(!c){box.textContent='직업과 등급을 선택하면 장착 효과를 표시합니다.';return}const rows=Object.entries(c.values).map(([key,val])=>`<span>${EFFECT_LABEL[key]||key} <b>${val}</b></span>`).join('');box.innerHTML=`<div class="effect-list">${rows||'<span>표시할 장착 효과 없음</span>'}</div><span class="effect-warning">동료 자체 공격과 조건부 스킬은 발동 조건·소환 주기 검증 전까지 DPS에 자동 합산하지 않습니다.</span>`}
const STAT_OPTIONS=[['NONE','없음'],['ATK_FLAT','공격력(+)'],['ATK_PCT','공격력%'],['MAIN_STAT_FLAT','주스탯(+)'],['MAIN_STAT_PCT','주스탯%'],['SUB_STAT_FLAT','부스탯(+)'],['DMG','데미지%'],['DMG_AMP','데미지 증폭%'],['FINAL_DMG','최종 데미지%'],['BOSS_DMG','보스 데미지%'],['NORMAL_DMG','일반 몬스터 데미지%'],['DEF_PEN','방어 관통력%'],['CRIT_RATE','크리티컬 확률%'],['CRIT_DMG','크리티컬 데미지%']];
const $=id=>document.getElementById(id); const n=id=>Number($(id)?.value||0); const clamp=(v,a,b)=>Math.min(b,Math.max(a,v)); const pct=v=>1+Number(v||0)/100; const fmt=v=>Number.isFinite(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:2}):'—';
function setStatus(text,kind=''){const el=$('dataStatus');el.textContent=text;el.className='status-strip '+kind;}
function snapshot(){const out={};document.querySelectorAll('input[id],select[id]').forEach(el=>{if(['presetName','presetSelect'].includes(el.id))return;out[el.id]=el.type==='checkbox'?el.checked:el.value});return out}
function applySnapshot(s){Object.entries(s||{}).forEach(([id,v])=>{const el=$(id);if(!el)return;if(el.type==='checkbox')el.checked=!!v;else el.value=v});renderAll();}
function saveLocal(){localStorage.setItem(STORE,JSON.stringify(snapshot()));}
function loadLocal(){try{const s=JSON.parse(localStorage.getItem(STORE)||'null');if(s)applySnapshot(s)}catch{}}
function profiles(){try{return JSON.parse(localStorage.getItem(STORE+'-profiles')||'{}')}catch{return {}}}
function saveProfiles(p){localStorage.setItem(STORE+'-profiles',JSON.stringify(p));renderProfileSelect()}
function renderProfileSelect(){const sel=$('presetSelect'),p=profiles();sel.innerHTML='<option value="">저장된 프리셋 없음</option>'+Object.keys(p).sort().map(k=>`<option value="${escapeHtml(k)}">${escapeHtml(k)}</option>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function optionSelect(value){return `<select class="option-stat">${STAT_OPTIONS.map(([id,label])=>`<option value="${id}" ${id===value?'selected':''}>${label}</option>`).join('')}</select>`}
function renderOptionRows(){for(const id of ['currentOptions','candidateOptions'])$(id).innerHTML=[0,1,2].map(i=>`<div class="option-row">${optionSelect('NONE')}<input class="option-value" type="number" step="0.01" value="0" aria-label="${id} 옵션 ${i+1} 값"></div>`).join('')}
function valuesFor(root){const out={};$(root).querySelectorAll('.option-row').forEach(row=>{const stat=row.querySelector('.option-stat').value;const val=Number(row.querySelector('.option-value').value||0);if(stat!=='NONE'&&val)out[stat]=(out[stat]||0)+val});return out}
function fillJobs(){const sel=$('job');const jobs=DATA.jobs?.jobs||{};Object.entries(jobs).forEach(([id])=>sel.insertAdjacentHTML('beforeend',`<option value="${id}">${JOB_NAMES[id]||id}</option>`));renderCompanionEffect()}
function stageRows(){const mode=$('stageMode')?.value||'hunt';return DATA.stageData?.[mode]||[]}
function fillStageChapters(){const sel=$('stageChapter');if(!sel)return;const chapters=[...new Set(stageRows().map(x=>x.chapter))].sort((a,b)=>a-b);const current=sel.value;const next=current||String(chapters[0]||'');sel.innerHTML='<option value="">챕터 선택</option>'+chapters.map(c=>`<option value="${c}">${c}장</option>`).join('');if(chapters.includes(Number(next)))sel.value=next;fillStages()}
function fillStages(){const chapter=Number($('stageChapter')?.value||0),sel=$('stageSelect');if(!sel)return;const rows=stageRows().filter(x=>!chapter||x.chapter===chapter);const current=sel.value;sel.innerHTML='<option value="">스테이지 선택</option>'+rows.map((x,i)=>`<option value="${x.stage}">${x.stage} · ${x.category||'일반'}</option>`).join('');if(rows.some(x=>x.stage===current))sel.value=current;applyStageTarget()}
function selectedStage(){const stage=$('stageSelect')?.value;return stage?stageRows().find(x=>x.stage===stage)||null:null}
function applyStageTarget(){const row=selectedStage();if(!row)return;const def=(Number(row.Defence_min||0)+Number(row.Defence_max||row.Defence_min||0))/2;const boss=row.category==='보스';const hpKey=$('stageMode').value==='trial'?(boss?'BossHp':'NormalHp'):'MaxHp';const hp=(Number(row[hpKey+'_min']||0)+Number(row[hpKey+'_max']||row[hpKey+'_min']||0))/2;if(def)$('targetDefense').value=def;if(hp)$('targetHp').value=hp;if($('targetType').value!=='pvp')$('targetType').value=boss?'boss':'normal';renderStageVerdict()}
function stageSensitivity(){const target=$('targetType').value;const candidates=[['공격력', 'ATK_FLAT',100],['데미지', 'DMG',10],[target==='boss'?'보스 데미지':'일반 몬스터 데미지',target==='boss'?'BOSS_DMG':'NORMAL_DMG',10],['방어 관통력','DEF_PEN',10],['주스탯','MAIN_STAT_FLAT',1000],['크리티컬 데미지','CRIT_DMG',10],['공격 속도','ATK_SPEED',10]];const base=calculate();return candidates.map(([name,stat,amount])=>({name,stat,amount,delta:calculate({[stat]:amount}).dps-base.dps})).sort((a,b)=>b.delta/a.amount-b.delta/a.amount)}
function renderStageVerdict(){const box=$('stageVerdict');if(!box)return;const row=selectedStage(),r=calculate(),hp=n('targetHp'),limit=n('stageTimeLimit');if(!row||!hp){box.className='stage-verdict';box.innerHTML='목표 스테이지를 선택하면 클리어 가능성과 병목을 진단합니다.';return}const total=r.dps*limit,ratio=hp?total/hp:0;const clear=total>=hp;const ranked=stageSensitivity().slice(0,3);box.className='stage-verdict '+(clear?'good':'warn');box.innerHTML=`<strong>${row.stage} 목표 · ${clear?'클리어 가능':'현재 화력 부족'}</strong><div class="stage-meta">${fmt(r.dps)} DPS × ${limit}초 = ${fmt(total)} · 적 HP ${fmt(hp)} · 필요 비율 ${ratio.toFixed(2)}배</div><div class="bottleneck-list"><span><b>1순위 병목</b><b>${escapeHtml(ranked[0]?.name||'분석 중')} +${fmt(ranked[0]?.delta||0)} DPS</b></span><span><b>2순위</b><b>${escapeHtml(ranked[1]?.name||'—')} +${fmt(ranked[1]?.delta||0)} DPS</b></span><span><b>3순위</b><b>${escapeHtml(ranked[2]?.name||'—')} +${fmt(ranked[2]?.delta||0)} DPS</b></span></div>`}
function readInputs(extra={}){const target=$('targetType').value;const job=DATA.jobs?.jobs?.[$('job').value]||{};const main=n('mainStat')*pct(n('mainStatPct'));const sub=n('subStat');const statBased=(main/100+sub/400);const stats={attackFlat:n('attackFlat'),attackPct:n('attackPct'),maxHp:n('maxHp'),playerDefense:n('playerDefense'),maxMp:n('maxMp'),evasion:n('evasion'),statusDamage:n('statusDamage'),buffDuration:n('buffDuration'),companionSummonDuration:n('companionSummonDuration'),fixedCooldownReductionSeconds:n('fixedCooldownReductionSeconds'),cooldownReductionPercent:n('cooldownReductionPercent'),basicAttackTargetCountIncrease:n('basicAttackTargetCountIncrease'),receivedDamageReduction:n('receivedDamageReduction'),mainStat:main,subStat:sub,statBased,damage:n('damage'),damageAmp:n('damageAmp'),finalDamage:n('finalDamage'),critRate:n('critRate'),critDamage:n('critDamage'),minDamage:n('minDamage'),maxDamage:n('maxDamage'),mastery:n('mastery'),skillCoefficient:n('skillCoefficient'),attackInterval:n('attackInterval'),attackSpeed:n('attackSpeed'),attackSpeedAdditions:[],defPenAdditions:[],targetDefense:n('targetDefense'),defPen:n('defPen'),bossDamage:n('bossDamage'),normalDamage:n('normalDamage'),targetTaken:n('targetTaken'),basicDamage:n('basicDamage'),skillDamage:n('skillDamage'),accuracy:n('accuracy'),skillLevels:{first:n('firstSkillLevel'),second:n('secondSkillLevel'),third:n('thirdSkillLevel'),fourth:n('fourthSkillLevel'),all:n('allSkillLevel')},masteries:{main80k:n('mainMasteryCount'),sub25k:n('subMasteryCount')},target,job,level:n('level')};
  Object.entries(extra).forEach(([k,v])=>{if(k==='MAIN_STAT_FLAT')stats.mainStat+=v;else if(k==='MAIN_STAT_PCT')stats.mainStat*=pct(v);else if(k==='SUB_STAT_FLAT')stats.subStat+=v;else if(k==='ATK_FLAT')stats.attackFlat+=v;else if(k==='ATK_PCT')stats.attackPct+=v;else if(k==='DMG')stats.damage+=v;else if(k==='DMG_AMP')stats.damageAmp+=v;else if(k==='FINAL_DMG')stats.finalDamage+=v;else if(k==='BOSS_DMG')stats.bossDamage+=v;else if(k==='NORMAL_DMG')stats.normalDamage+=v;else if(k==='DEF_PEN'){stats.defPenAdditions.push(Number(v)||0);stats.defPen+=Number(v)||0;}else if(k==='ATK_SPEED'){stats.attackSpeedAdditions.push(Number(v)||0);stats.attackSpeed+=Number(v)||0;}else if(k==='CRIT_RATE')stats.critRate+=v;else if(k==='CRIT_DMG')stats.critDamage+=v});
  const companion=selectedCompanionEffect();if(companion){for(const [key,val] of Object.entries(companion.values)){if(key==='attackPlus')stats.attackFlat+=Number(val)||0;else if(key==='maxDamage')stats.maxDamage+=Number(val)||0;else if(key==='bossDamage')stats.bossDamage+=Number(val)||0;else if(key==='normalDamage')stats.normalDamage+=Number(val)||0;else if(key==='basicDamage')stats.basicDamage+=Number(val)||0;else if(key==='skillDamage')stats.skillDamage+=Number(val)||0;else if(key==='attackSpeed'){stats.attackSpeedAdditions.push(Number(val)||0);stats.attackSpeed+=Number(val)||0;}else if(key==='critRate')stats.critRate+=Number(val)||0;else if(key==='critDamage')stats.critDamage+=Number(val)||0;else if(key==='minDamage')stats.minDamage+=Number(val)||0;else if(key==='mainPct')stats.mainStat*=pct(val)}}stats.statBased=stats.mainStat/100+stats.subStat/400;return stats;
}
function calculate(extra={}){return calculateDamage(readInputs(extra), DATA.combat||{});}
function calculatePower(){return calculateCombatPower(readInputs(), DATA.combat||{});}
function renderCombat(){const r=calculate();const power=calculatePower();$('avgDamage').textContent=fmt(r.average);$('damageRange').textContent=`최소 ${fmt(r.min)} · 최대 ${fmt(r.max)}`;$('dps').textContent=fmt(r.dps);$('dpsNote').textContent=`공속 점감 후 ${r.effectiveAttackSpeed.toFixed(2)}% · 보정 ×${r.speedFactor.toFixed(3)} · 간격 ${n('attackInterval')}초`;$('combatPower').textContent=fmt(power.power);$('combatPowerNote').textContent=power.provisional?`공식식 적용 · 미입력 보조 능력치 ${power.missingInputs.length}개는 0 처리`:'공식식 적용';$('defenseFactor').textContent=(r.defenseFactor*100).toFixed(2)+'%';$('defenseNote').textContent=`관통 점감 후 ${r.effectiveDefPen.toFixed(2)}% · 방어력 ${fmt(n('targetDefense'))} → ${fmt(r.afterDef)}`;$('statDamage').textContent=r.statBased.toFixed(2)+'%';$('combatBreakdown').innerHTML=`<div class="breakdown-grid"><span>공격력<b>${fmt(r.attack)}</b></span><span>치명타 기대 배율<b>×${(1+r.critChance*n('critDamage')/100).toFixed(3)}</b></span><span>대상 보정<b>${$('targetType').value==='boss'?n('bossDamage'):n('normalDamage')}%</b></span></div>`;renderStageVerdict();saveLocal()}
function renderCube(){const current=calculate(valuesFor('currentOptions'));const candidate=calculate(valuesFor('candidateOptions'));$('cubeCurrentDps').textContent=fmt(current.dps);$('cubeCandidateDps').textContent=fmt(candidate.dps);const delta=candidate.dps-current.dps;const rate=current.dps?delta/current.dps*100:0;$('cubeDelta').textContent=`${delta>=0?'+':''}${fmt(delta)} (${rate>=0?'+':''}${rate.toFixed(2)}%)`;const p=n('cubeProbability')/100,cost=n('cubeCost');$('cubeEconomics').innerHTML=p>0?`후보 1회 달성 기대 횟수 <b>${fmt(1/p)}회</b> · 기대 메소 <b>${fmt(1/p*cost)}</b><br><small>확률이 없는 값은 기대 비용을 계산하지 않습니다.</small>`:'등장 확률을 입력하면 기대 횟수와 비용을 계산합니다.'}
function renderProbability(){const r=probabilitySummary(n('successRate'),n('attempts'),n('attemptCost'));if(!r.probability&&r.expectedAttempts===Infinity){$('probabilityResult').innerHTML='<div class="big-prob">0%</div>성공 확률이 0이면 달성 확률과 기대값은 계산할 수 없습니다.';return}$('probabilityResult').innerHTML=`<div class="big-prob">${(r.probability*100).toFixed(4)}%</div><ul><li>${r.attempts}회 안에 1회 이상 성공할 확률: <b>${(r.probability*100).toFixed(4)}%</b></li><li>평균 기대 시도 횟수: <b>${fmt(r.expectedAttempts)}회</b></li><li>평균 기대 비용: <b>${r.expectedCost==null?'미입력':fmt(r.expectedCost)}</b></li><li>90% 달성 필요 횟수: <b>${r.need90}회</b></li><li>95% 달성 필요 횟수: <b>${r.need95}회</b></li></ul>`}
function renderAll(){renderCombat();renderCube();renderProbability()}
async function loadData(){try{const [combat,stats,jobs,probabilities,companionRuntime,companionRules,stageData]=await Promise.all([fetch('data/combat-rules.json').then(r=>r.json()),fetch('data/stat-rules.json').then(r=>r.json()),fetch('data/job-stats.json').then(r=>r.json()),fetch('data/probabilities.json').then(r=>r.json()),fetch('data/companion-runtime-data.json').then(r=>r.json()),fetch('data/companion-rules.json').then(r=>r.json()),fetch('data/stage-data.json').then(r=>r.json())]);Object.assign(DATA,{combat,stats,jobs,probabilities,companionRuntime,companionRules,stageData});fillJobs();fillStageChapters();loadLocal();fillStageChapters();renderCompanionEffect();$('probabilitySource').textContent=`공식 설정 확률 데이터 로드 완료 · ${probabilities?.source?.verificationStatus||'검증 상태 확인 필요'}`;setStatus(`공식 전투·능력치·확률 데이터 로드 완료 · 직업 매핑은 ${jobs.status||'provisional'}`, 'good');renderAll()}catch(e){setStatus('데이터 파일을 불러오지 못했습니다. 기본 입력으로 계산하지만 공식 데이터 상태를 확인하세요.','bad');$('probabilitySource').textContent='확률 데이터 로드 실패: '+e.message;renderAll()}}
function bind(){window.addEventListener('maple:presets-changed',()=>{renderCompanionEffect();renderAll()});document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===btn.dataset.tab))}));document.querySelectorAll('#characterForm input,#characterForm select,#targetForm input,#targetForm select').forEach(el=>el.addEventListener('input',()=>{renderCompanionEffect();if(['stageMode','stageChapter'].includes(el.id)){if(el.id==='stageMode')fillStageChapters();else fillStages()}else if(el.id==='stageSelect')applyStageTarget();renderCombat()}));$('calculateCombat').addEventListener('click',renderCombat);$('calculateCube').addEventListener('click',renderCube);$('calculateProbability').addEventListener('click',renderProbability);document.querySelectorAll('#currentOptions,#candidateOptions').forEach(el=>el.addEventListener('input',renderCube));$('saveQuick').addEventListener('click',()=>{saveLocal();$('activePresetLabel').textContent='현재 입력 저장됨';});$('resetAll').addEventListener('click',()=>{if(confirm('현재 입력을 초기화할까요?')){localStorage.removeItem(STORE);location.reload()}});$('savePreset').addEventListener('click',()=>{const name=$('presetName').value.trim();if(!name){alert('프리셋 이름을 입력하세요.');return}const p=profiles();p[name]=snapshot();saveProfiles(p);$('presetSelect').value=name;$('activePresetLabel').textContent=name;saveLocal()});$('loadPreset').addEventListener('click',()=>{const name=$('presetSelect').value,p=profiles();if(name&&p[name]){$('activePresetLabel').textContent=name;applySnapshot(p[name]);saveLocal()}});$('deletePreset').addEventListener('click',()=>{const name=$('presetSelect').value;if(!name)return;const p=profiles();delete p[name];saveProfiles(p);$('activePresetLabel').textContent='현재 입력'});}
renderOptionRows();renderProfileSelect();bind();loadData();renderAll();
